import {useEffect,useState} from 'react'; import {useNavigate,useParams} from 'react-router-dom'; import {AlertTriangle,ArrowLeft,CheckCircle2,ChevronDown,Eye,FileClock,GitMerge,Play,Plus,Save,Send,Trash2,XCircle,Zap} from 'lucide-react'; import {FlowCanvas} from '../components/FlowCanvas'; import {useAppStore} from '../store/useAppStore'; import type {PublishResult} from '../types'; import type {FlowNode,NodeKind} from '../types';
const palette:[NodeKind,string,string][]=[['start','开始','流程入口'],['form','表单填写','收集业务数据'],['approval','审批','人工审批任务'],['condition','条件分支','按规则分流'],['automation','自动化','执行本地动作'],['notify','通知','发送站内通知'],['end','结束','流程终点']];
export function Editor(){
 const {id}=useParams(),nav=useNavigate();
 const store=useAppStore();
 const w=store.workflows.find(x=>x.id===store.currentId)||store.workflows[0];
 const selected=w.nodes.find(n=>n.id===store.selectedNodeId);
 const [result,setResult]=useState<PublishResult|null>(null);
 useEffect(()=>{if(id&&id!==store.currentId){store.setCurrent(id);setResult(null)}},[id]);
 const add=(type:NodeKind)=>{const node:FlowNode={id:type+'-'+Date.now(),type,position:{x:350+Math.random()*200,y:200+Math.random()*150},data:{label:palette.find(x=>x[0]===type)![1],state:'unconfigured',config:{}}};store.updateNodes([...w.nodes,node])};
 const publish=()=>{const r=store.publish();setResult(r)};
 const stale=w.draftBaseRevision!==w.revision;
 return <div className="editor-page"><div className="editor-top"><button className="icon-btn" onClick={()=>nav('/workflows')}><ArrowLeft/></button><div className="editor-title"><small>流程管理 / {w.domain}</small><b>{w.name}</b></div><span className={'draft-indicator '+(stale?'stale':'')} data-testid="draft-indicator">{w.status==='draft'?'● 草稿':'✓ 已发布'} · 运行版本 v{w.revision} · 草稿基于 v{w.draftBaseRevision}{stale&&' · 落后'}</span><div className="editor-actions"><button className="secondary" onClick={store.save}><Save/>保存草稿</button><button className="secondary" data-testid="validate-button" onClick={store.runValidation}><Play/>运行校验</button><button className="secondary" onClick={()=>nav(`/workflows/${w.id}/preview`)}><Eye/>预览</button><button className="secondary" onClick={()=>nav(`/workflows/${w.id}/versions`)}><FileClock/>版本历史</button><button data-testid="publish-button" onClick={publish}><Send/>发布</button></div></div>
 {result&&!result.ok&&result.reason==='conflict'&&<div className="publish-banner conflict" data-testid="publish-conflict"><AlertTriangle/><div><b>发布冲突 —— 草稿已保留</b><p>服务端当前为 v{result.serverVersion}，你的草稿基于更早的版本。两个窗口同时提交发布时仅一个成功，本窗口未写入任何内容。可查看版本差异后合并最新配置重新发布。</p></div><button onClick={()=>nav(`/workflows/${w.id}/versions`)}><FileClock/>查看版本差异</button><button data-testid="rebase-draft" onClick={()=>{store.rebaseDraft();setResult(null)}}><GitMerge/>合并最新 v{result.serverVersion} 后重提</button><button className="secondary" data-testid="retry-publish" onClick={publish}>保留草稿直接重提</button></div>}
 {result&&!result.ok&&result.reason==='write-failed'&&<div className="publish-banner failed" data-testid="publish-failed"><XCircle/><div><b>发布事务写入失败 —— 已整体回滚</b><p>流程、版本记录与运行实例均已恢复到发布前，目标版本号 v{result.retryVersion} 仍然可用，修复后可直接用同一版本号重新提交。</p></div><button data-testid="retry-publish" onClick={publish}>用 v{result.retryVersion} 重新提交</button></div>}
 <div className="editor-body"><aside className="node-library"><div className="pane-title"><b>节点组件</b><small>点击添加到画布</small></div><div className="node-search">搜索节点组件</div><h4>基础节点</h4>{palette.map(([type,label,desc])=><button key={type} className={'palette '+type} onClick={()=>add(type)}><span>+</span><div><b>{label}</b><small>{desc}</small></div></button>)}<div className="library-tip"><b>使用提示</b><p>拖动节点调整布局，从端点连接下一步骤。</p></div>
 <div className="publish-lab" data-testid="publish-lab"><div className="lab-head"><Zap/><b>发布事务演练</b></div><p>在浏览器单页中模拟多人多窗口发布：</p>
 <label className="lab-check"><input type="checkbox" data-testid="arm-failure" checked={store.failNextWrite} onChange={e=>store.armWriteFailure(e.target.checked)}/><span><b>下次发布写入失败</b><small>模拟版本表落库异常，验证流程/版本/实例整体回滚与同版本号重提</small></span></label>
 <button className="secondary lab-btn" data-testid="peer-publish" onClick={()=>store.peerPublish()}><GitMerge/>模拟另一窗口先发布</button>
 {stale&&<button className="secondary lab-btn" data-testid="rebase-draft-lab" onClick={()=>{store.rebaseDraft();setResult(null)}}><GitMerge/>合并最新 v{w.revision} 到草稿</button>}
 {store.failNextWrite&&<div className="lab-armed" data-testid="lab-armed">● 已注入写入故障，下一次发布会失败并回滚</div>}
 <small className="lab-meta">服务端修订版本 revision=v{w.revision}；本窗口草稿基线 v{w.draftBaseRevision}{stale?'（已落后，发布会冲突）':'（一致，可发布）'}</small>
 </div>
 </aside><section className="editor-center"><div className="canvas-bar"><span>主流程（草稿）</span><span className="spacer"/><button className="icon-btn">−</button><small>100%</small><button className="icon-btn">＋</button></div>{w.nodes.length?<FlowCanvas nodes={w.nodes} edges={w.edges} onNodes={store.updateNodes} onEdges={store.updateEdges} onSelect={store.selectNode}/>:<div className="blank-flow"><div>⌘</div><b>从一个开始节点构建流程</b><p>在左侧点击节点组件，将它添加到画布。</p><button onClick={()=>add('start')}><Plus/>添加开始节点</button></div>}</section><ConfigPanel node={selected} update={store.updateConfig}/></div><section className="issues" data-testid="issues-panel"><div className="issues-head"><b>问题面板</b><span className="error-count" data-testid="error-count">{store.issues.filter(i=>i.level==='error').length} 错误</span><span>{store.issues.filter(i=>i.level==='warning').length} 警告</span><span className="spacer"/><small>上次校验：刚刚</small><ChevronDown/></div>{store.issues.length>0&&<div className="issue-list">{store.issues.map((i,k)=><button key={i.nodeId+'-'+k} onClick={()=>store.selectNode(i.nodeId)}><XCircle/><b>{i.message}</b><small>节点：{w.nodes.find(n=>n.id===i.nodeId)?.data.label||'流程'}</small><span>定位 →</span></button>)}</div>}</section></div>}
function ConfigPanel({node,update}:{node?:FlowNode;update:(id:string,c:Record<string,any>)=>void}){const [saved,setSaved]=useState(false);if(!node)return <aside className="config-panel empty-config"><div>◫</div><b>选择一个节点</b><p>在画布中选择节点以查看和编辑配置。</p></aside>;const c=node.data.config, set=(v:Record<string,any>)=>{update(node.id,v);setSaved(false)};return <aside className="config-panel" data-testid="config-panel"><div className="config-head"><div><small>{node.type.toUpperCase()} NODE</small><h3>{node.data.label}</h3></div><button className="icon-btn"><Trash2/></button></div><label>节点名称<input value={node.data.label} readOnly/></label>{node.type==='approval'&&<><h4>审批配置</h4><label>审批人来源<select aria-label="审批人来源" value={c.approverSource||''} onChange={e=>set({approverSource:e.target.value})}><option value="">请选择审批人来源</option><option>直属主管</option><option>固定角色</option><option>指定成员</option><option>表单字段</option></select></label>{c.approverSource==='固定角色'&&<label>审批角色<select onChange={e=>set({role:e.target.value})}><option>财务审批人</option><option>部门负责人</option><option>法务经理</option></select></label>}<label>审批说明<textarea rows={5} value={c.instruction||''} onChange={e=>set({instruction:e.target.value})} placeholder="输入审批说明"/></label></>}{node.type==='condition'&&<><h4>分支规则</h4><label>判断字段<select aria-label="条件字段" value={c.ruleType||''} onChange={e=>set({ruleType:e.target.value})}><option value="">请选择字段</option><option value="amount">申请金额</option><option value="department">部门</option><option value="attachment">附件</option></select></label><div className="form-row"><label>运算符<select value={c.operator||'>'} onChange={e=>set({operator:e.target.value})}><option>&gt;</option><option>=</option><option>为空</option></select></label><label>比较值<input aria-label="条件比较值" type="number" value={c.value||''} onChange={e=>set({value:Number(e.target.value)})}/></label></div><div className="branch-card"><b>分支 1</b><span>满足规则</span></div><div className="branch-card"><b>分支 2</b><span>其他情况</span></div></>}{node.type==='form'&&<><h4>表单字段</h4>{(c.fields||[]).map((f:any)=><div key={f.id} className="field-chip"><b>{f.label}</b><small>{f.type} · {f.required?'必填':'选填'}</small></div>)}</>}{node.type==='automation'&&<><h4>本地动作</h4><label>执行动作<select value={c.action||''} onChange={e=>set({action:e.target.value})}><option>创建工单</option><option>发送 Webhook（模拟）</option><option>写入系统记录</option></select></label></>}{node.type==='notify'&&<><h4>通知设置</h4><label>通知对象<input value={c.targets||''} onChange={e=>set({targets:e.target.value})}/></label><label>消息模板<textarea value={c.template||''} onChange={e=>set({template:e.target.value})}/></label></>}<div className="config-footer"><span>{saved?<><CheckCircle2/>配置已保存</>:'尚有未保存更改'}</span><button data-testid="save-node-config" onClick={()=>setSaved(true)}>保存配置</button></div></aside>}
