import {useMemo,useState} from 'react';import {useNavigate,useSearchParams} from 'react-router-dom';import {Activity,AlertTriangle,Clock,GitCompare,Play,Search,X} from 'lucide-react';import {PageTitle,Status} from '../components/common';import {FlowCanvas} from '../components/FlowCanvas';import {useAppStore} from '../store/useAppStore';import {diffVersions,resolveInstanceFlow} from '../store/versioning';
import type {Instance} from '../types';

export function Monitor(){
 const ins=useAppStore(s=>s.instances),ws=useAppStore(s=>s.workflows),startInstance=useAppStore(s=>s.startInstance);
 const [params]=useSearchParams();
 const [filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(params.get('instance')),[newFlow,setNewFlow]=useState('wf-1');
 const published=ws.filter(w=>w.status==='published');
 const rows=useMemo(()=>ins.filter(i=>filter==='all'||i.status===filter),[ins,filter]);
 const launch=()=>{try{const created=startInstance(newFlow);setFilter('all');setSelected(created.id);}catch{/* 失败 toast 已提示 */}};
 return <div className="page"><PageTitle eyebrow="运行中心" title="Runtime Monitor" desc="实例按启动时冻结的版本执行：新版本发布只对新实例生效，运行中实例继续走旧版本。"/><section className="monitor-kpis">{[['运行中',ins.filter(i=>i.status==='running').length,Activity],['异常',ins.filter(i=>i.status==='abnormal').length,AlertTriangle],['超时',ins.filter(i=>i.status==='timeout').length,Clock],['今日完成',ins.filter(i=>i.status==='completed').length,Activity]].map(([a,b,I]:any)=><article key={a}><I/><span><small>{a}</small><b>{b}</b></span></article>)}</section><div className="toolbar panel"><div className="search"><Search/><input placeholder="搜索实例或申请人"/></div>{[['all','全部'],['abnormal','异常'],['timeout','超时'],['running','进行中'],['completed','已完成']].map(([v,l])=><button key={v} className={'filter '+(filter===v?'active':'')} onClick={()=>setFilter(v)}>{l}</button>)}<span className="spacer"/><select aria-label="选择流程发起新实例" value={newFlow} onChange={e=>setNewFlow(e.target.value)}>{published.map(w=><option key={w.id} value={w.id}>{w.name} · 最新 v{w.version}</option>)}</select><button data-testid="start-instance" onClick={launch}><Play/>发起实例（按最新版本）</button></div><section className="panel monitor-table">{rows.length?<table><thead><tr><th>实例编号</th><th>申请人</th><th>业务域</th><th>当前节点</th><th>采用版本</th><th>状态</th><th>提交时间</th><th>耗时</th><th>风险</th></tr></thead><tbody>{rows.map(i=>{const wf=ws.find(w=>w.id===i.workflowId);const latestV=wf&&wf.versions.length?Math.max(...wf.versions.map(v=>v.version)):(wf?.version??0);const outdated=i.version<latestV;return <tr key={i.id} data-testid="instance-row" onClick={()=>setSelected(i.id)}><td><b>{i.id}</b></td><td>{i.applicant}</td><td>{i.domain}</td><td>{i.currentNode}</td><td><span className={'pin-version '+(outdated?'outdated':'current')} data-testid="instance-version">v{i.version}{outdated&&<em>旧版本</em>}</span></td><td><Status value={i.status}/></td><td>{i.submittedAt}</td><td>{i.duration}</td><td><Status value={i.risk}/></td></tr>})}</tbody></table>:<div className="empty"><b>没有匹配的实例</b></div>}</section>{(()=>{const item=ins.find(i=>i.id===selected);return item?<InstanceDrawer key={item.id} item={item} onClose={()=>setSelected(null)}/>:null;})()}</div>;
}

function InstanceDrawer({item,onClose}:{item:Instance;onClose:()=>void}){
 const ws=useAppStore(s=>s.workflows);const nav=useNavigate();
 const flow=ws.find(w=>w.id===item.workflowId)!;
 const {nodes,edges,snapshot,latest,outdated}=resolveInstanceFlow(flow,item);
 const diff=useMemo(()=>snapshot&&latest?diffVersions(snapshot,latest):null,[item.id,flow.version]);
 const highlight=nodes.find(n=>n.data.label===item.currentNode)?.id;
 return <div className="drawer-backdrop"><aside className="instance-drawer" data-testid="instance-detail"><div className="drawer-head"><div><small>流程实例详情</small><h2>{item.id}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="detail-meta"><div><small>申请人</small><b>{item.applicant}</b></div><div><small>状态</small><Status value={item.status}/></div><div><small>耗时</small><b>{item.duration}</b></div><div><small>风险</small><Status value={item.risk}/></div></div><div className={'version-banner '+(outdated?'outdated':'current')} data-testid="detail-version"><div><small>实例采用的执行版本</small><b>v{item.version} · {snapshot?.createdAt||'—'}</b></div><span>{outdated?<>发布后未迁移：继续按 v{item.version} 快照执行；流程当前已发布 <b>v{latest!.version}</b>，仅新实例采用</>:<>当前为最新发布版本</>}</span>{outdated&&<button className="text" data-testid="goto-compare" onClick={()=>nav(`/workflows/${flow.id}/versions?from=${item.version}&to=${latest!.version}`)}><GitCompare/>查看与最新版差异 →</button>}</div>{outdated&&diff&&<div className="version-diff-mini" data-testid="detail-diff"><GitCompare/><span>相对 v{latest!.version}：</span><span className="added">新增 {diff.added.length}</span><span className="removed">删除 {diff.removed.length}</span><span className="changed">配置变化 {diff.changed.length}</span><span>连线变化 {diff.edgeDelta}</span></div>}<h3>执行流程（v{item.version} 冻结快照）</h3><div className="runtime-canvas"><FlowCanvas nodes={nodes} edges={edges} onNodes={()=>{}} onEdges={()=>{}} onSelect={()=>{}} highlight={highlight}/></div><h3>执行时间线</h3><div className="timeline" data-testid="execution-timeline">{item.timeline.map(t=><div key={t.title} className={t.status}><i/><span><b>{t.title}</b><small>{t.time}</small></span><Status value={t.status}/></div>)}</div></aside></div>;
}
