import {useMemo,useState} from 'react';import {useNavigate,useParams,useSearchParams} from 'react-router-dom';import {ArrowLeft,GitCompare,History,RotateCcw} from 'lucide-react';import {PageTitle} from '../components/common';import {useAppStore} from '../store/useAppStore';import {diffVersions,runningOnVersion} from '../store/versioning';
export function Versions(){
 const {id}=useParams(),nav=useNavigate(),[params]=useSearchParams();
 const store=useAppStore(),w=store.workflows.find(x=>x.id===id)!;
 const instances=store.instances;
 const all=[...w.versions].sort((a,b)=>b.version-a.version);
 const queryFrom=Number(params.get('from'))||0,queryTo=Number(params.get('to'))||0;
 const defaultLeft=all.at(-1)?.version||1,defaultRight=all[0]?.version||w.version;
 const [left,setLeft]=useState(queryFrom||defaultLeft),[right,setRight]=useState(queryTo||defaultRight);
 const a=all.find(v=>v.version===left),b=all.find(v=>v.version===right);
 const diff=useMemo(()=>diffVersions(a,b),[a,b]);
 const restore=()=>{store.setCurrent(w.id);store.restore(left);nav(`/workflows/${w.id}`)};
 return <div className="page versions-page"><button className="back-link" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/>返回编辑器</button><PageTitle eyebrow="流程版本" title="Version History" desc={`${w.name} · 版本快照发布后冻结不可变；运行中实例继续钉在各自版本上。`}/><div className="version-layout"><aside className="panel version-list"><h3><History/>版本记录</h3>{all.map((v,i)=>{const running=runningOnVersion(instances,w.id,v.version);return <button key={v.version} className={v.version===right?'active':''} onClick={()=>setRight(v.version)}><span><b>v{v.version}</b>{v.version===w.version&&<em>当前</em>}</span><small>{v.createdAt}</small><p>{v.note}</p><small className="running-pin" data-testid="running-count">{running>0?`${running} 个进行中实例仍在执行此版本`:'无运行中实例'}</small></button>;})}</aside><section className="panel compare" data-testid="version-compare"><div className="compare-head"><div><GitCompare/><h2>版本对比</h2></div><button className="secondary" data-testid="restore-version" onClick={restore}><RotateCcw/>恢复 v{left} 为草稿</button></div><div className="compare-select"><label>基准版本（旧依据）<select value={left} onChange={e=>setLeft(Number(e.target.value))}>{all.map(v=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}{runningOnVersion(instances,w.id,v.version)?` · ${runningOnVersion(instances,w.id,v.version)} 实例运行中`:''}</option>)}</select></label><span>→</span><label>比较版本<select value={right} onChange={e=>setRight(Number(e.target.value))}>{all.map(v=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}</option>)}</select></label></div><div className="diff-summary"><article><small>新增节点</small><b>{diff.added.length}</b></article><article><small>删除节点</small><b>{diff.removed.length}</b></article><article><small>配置变化</small><b>{diff.changed.length}</b></article><article><small>连线变化</small><b>{diff.edgeDelta}</b></article></div><div className="diff-list"><h3>变更明细</h3>{diff.added.map(n=><div key={n.id} className="diff added"><span>＋ 新增</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.removed.map(n=><div key={n.id} className="diff removed"><span>− 删除</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.changed.map(n=><div key={n.id} className="diff changed"><span>~ 配置</span><b>{n.data.label}</b><small>节点配置已更新</small></div>)}{!diff.added.length&&!diff.removed.length&&!diff.changed.length&&!diff.edgeDelta&&<div className="empty-diff">这两个版本的节点结构一致</div>}<div className="release-note"><small>发布说明</small><p>{b?.note}</p></div></div></section></div></div>}
